[package]
name = "http_server"
version = "1.0.0"
edition = "2021"
[dependencies]
tokio = { version = "1.22.0", features = ["full"] }
warp = {version = "0.3.3", features=["compression"]}
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "*"
rs-parse-snapshot = { path = "../parse"}

