[package]
authors = ["yuuangzhang"]
edition = "2021"
name = "debug"
version = "1.0.6"


[dependencies]
rs-parse-snapshot = { path = "../parse"}
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "*"