[package]
authors = ["yuuangzhang"]
edition = "2021"
name = "v8-profiler-rs"
version = "1.0.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
rs-parse-snapshot = { path = "../parse"}
wasm-bindgen = "0.2.63"
js-sys = "^0.3.0"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "*"
[dev-dependencies]
wasm-bindgen-test = "0.3.13"
